apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user
spec:
  selector:
    matchLabels:
      run: api-user
  replicas: 2
  template:
    metadata:
      labels:
        run: api-user
    spec:
      containers:
      - name: api-user
        image: docker.io/omarkhalil10/udagram-api-user:v4a
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m