apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-feed
spec:
  selector:
    matchLabels:
      run: api-feed
  replicas: 2
  template:
    metadata:
      labels:
        run: api-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: omarkhalil10/udagram-api-feed:v4a
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m