apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  selector:
    matchLabels:
      name: reverseproxy
  replicas: 2
  template:
    metadata:
      labels:
        name: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: omarkhalil10/reverseproxy:v4a
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m